<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
    use Carbon\Carbon;


class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
     
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '001','bank'=>'001 - BCO DO BRASIL S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '003','bank'=>'003 - BCO DA AMAZONIA S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '004','bank'=>'004 - BCO DO NORDESTE DO BRASIL S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '007','bank'=>'007 - BNDES']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '010','bank'=>'010 - CREDICOAMO']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '011','bank'=>'011 - C.SUISSE HEDGING-GRIFFO CV S/A']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '012','bank'=>'012 - BANCO INBURSA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '014','bank'=>'014 - STATE STREET BR S.A. BCO COMERCIAL']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '015','bank'=>'015 - UBS BRASIL CCTVM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '016','bank'=>'016 - CCM DESP TRÂNS SC E RS']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '017','bank'=>'017 - BNY MELLON BCO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '018','bank'=>'018 - BCO TRICURY S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '021','bank'=>'021 - BCO BANESTES S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '024','bank'=>'024 - BCO BANDEPE S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '025','bank'=>'025 - BCO ALFA S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '029','bank'=>'029 - BANCO ITAÚ CONSIGNADO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '033','bank'=>'033 - BCO SANTANDER (BRASIL) S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '036','bank'=>'036 - BCO BBI S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '037','bank'=>'037 - BCO DO EST. DO PA S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '040','bank'=>'040 - BCO CARGILL S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '041','bank'=>'041 - BCO DO ESTADO DO RS S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '047','bank'=>'047 - BCO DO EST. DE SE S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '060','bank'=>'060 - CONFIDENCE CC S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '062','bank'=>'062 - HIPERCARD BM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '063','bank'=>'063 - BANCO BRADESCARD']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '064','bank'=>'064 - GOLDMAN SACHS DO BRASIL BM S.A']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '065','bank'=>'065 - BCO ANDBANK S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '066','bank'=>'066 - BCO MORGAN STANLEY S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '069','bank'=>'069 - BCO CREFISA S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '070','bank'=>'070 - BRB - BCO DE BRASILIA S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '074','bank'=>'074 - BCO. J.SAFRA S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '075','bank'=>'075 - BCO ABN AMRO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '076','bank'=>'076 - BCO KDB BRASIL S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '077','bank'=>'077 - BANCO INTER']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '078','bank'=>'078 - HAITONG BI DO BRASIL S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '079','bank'=>'079 - PICPAY BANK - BANCO MÚLTIPLO S.A']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '080','bank'=>'080 - B&T CC LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '081','bank'=>'081 - BANCOSEGURO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '082','bank'=>'082 - BANCO TOPÁZIO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '083','bank'=>'083 - BCO DA CHINA BRASIL S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '084','bank'=>'084 - UNIPRIME DO BRASIL - COOP']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '085','bank'=>'085 - COOPCENTRAL AILOS']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '088','bank'=>'088 - BANCO RANDON S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '089','bank'=>'089 - CREDISAN CC']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '091','bank'=>'091 - CCCM UNICRED CENTRAL RS']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '092','bank'=>'092 - BRK S.A. CFI']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '093','bank'=>'093 - POLOCRED SCMEPP LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '094','bank'=>'094 - BANCO FINAXIS']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '095','bank'=>'095 - TRAVELEX BANCO DE CÂMBIO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '096','bank'=>'096 - BCO B3 S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '097','bank'=>'097 - CREDISIS CENTRAL DE COOPERATIVAS DE CRÉDITO LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '098','bank'=>'098 - CREDIALIANÇA CCR']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '099','bank'=>'099 - UNIPRIME COOPCENTRAL LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '100','bank'=>'100 - PLANNER CV S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '101','bank'=>'101 - RENASCENCA DTVM LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '102','bank'=>'102 - XP INVESTIMENTOS CCTVM S/A']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '104','bank'=>'104 - CAIXA ECONOMICA FEDERAL']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '105','bank'=>'105 - LECCA CFI S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '107','bank'=>'107 - BCO BOCOM BBM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '108','bank'=>'108 - PORTOCRED S.A. - CFI']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '111','bank'=>'111 - OLIVEIRA TRUST DTVM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '113','bank'=>'113 - NEON CTVM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '114','bank'=>'114 - CENTRAL COOPERATIVA DE CRÉDITO NO ESTADO DO ESPÍRITO SANTO']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '117','bank'=>'117 - ADVANCED CC LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '119','bank'=>'119 - BCO WESTERN UNION']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '120','bank'=>'120 - BCO RODOBENS S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '121','bank'=>'121 - BCO AGIBANK S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '122','bank'=>'122 - BCO BRADESCO BERJ S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '124','bank'=>'124 - BCO WOORI BANK DO BRASIL S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '125','bank'=>'125 - BANCO GENIAL']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '126','bank'=>'126 - BR PARTNERS BI']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '127','bank'=>'127 - CODEPE CVC S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '128','bank'=>'128 - MS BANK S.A. BCO DE CÂMBIO']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '129','bank'=>'129 - UBS BRASIL BI S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '130','bank'=>'130 - CARUANA SCFI']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '131','bank'=>'131 - TULLETT PREBON BRASIL CVC LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '132','bank'=>'132 - ICBC DO BRASIL BM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '133','bank'=>'133 - CRESOL CONFEDERAÇÃO']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '134','bank'=>'134 - BGC LIQUIDEZ DTVM LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '136','bank'=>'136 - CONF NAC COOP CENTRAIS UNICRED']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '138','bank'=>'138 - GET MONEY CC LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '139','bank'=>'139 - INTESA SANPAOLO BRASIL S.A. BM']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '140','bank'=>'140 - NU INVEST CORRETORA DE VALORES S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '142','bank'=>'142 - BROKER BRASIL CC LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '143','bank'=>'143 - TREVISO CC S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '144','bank'=>'144 - BEXS BCO DE CAMBIO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '145','bank'=>'145 - LEVYCAM CCV LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '146','bank'=>'146 - GUITTA CC LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '149','bank'=>'149 - FACTA S.A. CFI']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '157','bank'=>'157 - ICAP DO BRASIL CTVM LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '159','bank'=>'159 - CASA CREDITO S.A. SCM']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '163','bank'=>'163 - COMMERZBANK BRASIL S.A. - BCO MÚLTIPLO']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '173','bank'=>'173 - BRL TRUST DTVM SA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '174','bank'=>'174 - PEFISA S.A. - C.F.I.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '177','bank'=>'177 - GUIDE']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '180','bank'=>'180 - CM CAPITAL MARKETS CCTVM LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '183','bank'=>'183 - SOCRED SA - SCMEPP']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '184','bank'=>'184 - BCO ITAÚ BBA S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '188','bank'=>'188 - ATIVA S.A. INVESTIMENTOS CCTVM']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '189','bank'=>'189 - HS FINANCEIRA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '190','bank'=>'190 - SERVICOOP']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '191','bank'=>'191 - NOVA FUTURA CTVM LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '194','bank'=>'194 - PARMETAL DTVM LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '195','bank'=>'195 - VALOR SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '196','bank'=>'196 - FAIR CC S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '197','bank'=>'197 - STONE IP S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '208','bank'=>'208 - BANCO BTG PACTUAL S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '212','bank'=>'212 - BANCO ORIGINAL']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '213','bank'=>'213 - BCO ARBI S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '217','bank'=>'217 - BANCO JOHN DEERE S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '218','bank'=>'218 - BCO BS2 S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '222','bank'=>'222 - BCO CRÉDIT AGRICOLE BR S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '224','bank'=>'224 - BCO FIBRA S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '233','bank'=>'233 - BANCO CIFRA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '237','bank'=>'237 - BCO BRADESCO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '241','bank'=>'241 - BCO CLASSICO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '243','bank'=>'243 - BANCO MASTER']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '246','bank'=>'246 - BCO ABC BRASIL S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '249','bank'=>'249 - BANCO INVESTCRED UNIBANCO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '250','bank'=>'250 - BCV - BCO CRÉDITO E VAREJO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '253','bank'=>'253 - BEXS CC S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '254','bank'=>'254 - PARANA BCO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '259','bank'=>'259 - MONEYCORP BCO DE CÂMBIO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '260','bank'=>'260 - NU PAGAMENTOS - IP']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '265','bank'=>'265 - BCO FATOR S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '266','bank'=>'266 - BCO CEDULA S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '268','bank'=>'268 - BARI CIA HIPOTECÁRIA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '269','bank'=>'269 - BCO HSBC S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '270','bank'=>'270 - SAGITUR CC']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '271','bank'=>'271 - IB CCTVM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '272','bank'=>'272 - AGK CC S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '273','bank'=>'273 - CCR DE SÃO MIGUEL DO OESTE']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '274','bank'=>'274 - MONEY PLUS SCMEPP LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '276','bank'=>'276 - BCO SENFF S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '278','bank'=>'278 - GENIAL INVESTIMENTOS CVM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '279','bank'=>'279 - COOP DE PRIMAVERA DO LESTE']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '280','bank'=>'280 - WILL FINANCEIRA S.A.CFI']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '281','bank'=>'281 - CCR COOPAVEL']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '283','bank'=>'283 - RB INVESTIMENTOS DTVM LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '285','bank'=>'285 - FRENTE CC LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '286','bank'=>'286 - CCR DE OURO']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '288','bank'=>'288 - CAROL DTVM LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '289','bank'=>'289 - EFX CC LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '290','bank'=>'290 - PAGSEGURO INTERNET IP S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '292','bank'=>'292 - BS2 DTVM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '293','bank'=>'293 - LASTRO RDV DTVM LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '296','bank'=>'296 - OZ CORRETORA DE CÂMBIO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '298','bank'=>'298 - VIPS CC LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '299','bank'=>'299 - BCO SOROCRED S.A. - BM']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '300','bank'=>'300 - BCO LA NACION ARGENTINA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '301','bank'=>'301 - BPP IP S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '306','bank'=>'306 - PORTOPAR DTVM LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '307','bank'=>'307 - TERRA INVESTIMENTOS DTVM']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '309','bank'=>'309 - CAMBIONET CC LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '310','bank'=>'310 - VORTX DTVM LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '311','bank'=>'311 - DOURADA CORRETORA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '312','bank'=>'312 - HSCM SCMEPP LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '313','bank'=>'313 - AMAZÔNIA CC LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '315','bank'=>'315 - PI DTVM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '318','bank'=>'318 - BCO BMG S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '319','bank'=>'319 - OM DTVM LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '320','bank'=>'320 - BCO CCB BRASIL S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '321','bank'=>'321 - CREFAZ SCMEPP LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '322','bank'=>'322 - CCR DE ABELARDO LUZ']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '323','bank'=>'323 - MERCADO PAGO IP LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '324','bank'=>'324 - CARTOS SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '325','bank'=>'325 - ÓRAMA DTVM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '326','bank'=>'326 - PARATI - CFI S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '328','bank'=>'328 - CECM FABRIC CALÇADOS SAPIRANGA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '329','bank'=>'329 - QI SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '330','bank'=>'330 - BANCO BARI S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '331','bank'=>'331 - FRAM CAPITAL DTVM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '332','bank'=>'332 - ACESSO SOLUCOES PAGAMENTO SA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '335','bank'=>'335 - BANCO DIGIO']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '336','bank'=>'336 - BCO C6 S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '340','bank'=>'340 - SUPERDIGITAL I.P. S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '341','bank'=>'341 - ITAÚ UNIBANCO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '342','bank'=>'342 - CREDITAS SCD']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '343','bank'=>'343 - FFA SCMEPP LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '348','bank'=>'348 - BCO XP S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '349','bank'=>'349 - AL5 S.A. CFI']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '350','bank'=>'350 - CREHNOR LARANJEIRAS']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '352','bank'=>'352 - TORO CTVM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '354','bank'=>'354 - NECTON INVESTIMENTOS S.A CVM']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '355','bank'=>'355 - ÓTIMO SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '358','bank'=>'358 - MIDWAY S.A. - SCFI']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '359','bank'=>'359 - ZEMA CFI S/A']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '360','bank'=>'360 - TRINUS CAPITAL DTVM']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '362','bank'=>'362 - CIELO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '363','bank'=>'363 - SINGULARE CTVM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '364','bank'=>'364 - GERENCIANET']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '365','bank'=>'365 - SIMPAUL']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '366','bank'=>'366 - BCO SOCIETE GENERALE BRASIL']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '367','bank'=>'367 - VITREO DTVM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '368','bank'=>'368 - BCO CSF S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '370','bank'=>'370 - BCO MIZUHO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '371','bank'=>'371 - WARREN CVMC LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '373','bank'=>'373 - UP.P SEP S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '374','bank'=>'374 - REALIZE CFI S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '376','bank'=>'376 - BCO J.P. MORGAN S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '377','bank'=>'377 - BMS SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '378','bank'=>'378 - BCO BRASILEIRO DE CRÉDITO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '379','bank'=>'379 - CECM COOPERFORTE']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '380','bank'=>'380 - PICPAY']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '381','bank'=>'381 - BCO MERCEDES-BENZ S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '382','bank'=>'382 - FIDUCIA SCMEPP LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '383','bank'=>'383 - EBANX IP LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '384','bank'=>'384 - GLOBAL SCM LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '385','bank'=>'385 - CECM DOS TRAB.PORT. DA G.VITOR']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '386','bank'=>'386 - NU FINANCEIRA S.A. CFI']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '387','bank'=>'387 - BCO TOYOTA DO BRASIL S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '389','bank'=>'389 - BCO MERCANTIL DO BRASIL S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '390','bank'=>'390 - BCO GM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '391','bank'=>'391 - CCR DE IBIAM']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '393','bank'=>'393 - BCO VOLKSWAGEN S.A']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '394','bank'=>'394 - BCO BRADESCO FINANC. S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '395','bank'=>'395 - F D GOLD DTVM LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '396','bank'=>'396 - HUB PAGAMENTOS']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '397','bank'=>'397 - LISTO SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '398','bank'=>'398 - IDEAL CTVM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '399','bank'=>'399 - KIRTON BANK']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '400','bank'=>'400 - COOP CREDITAG']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '401','bank'=>'401 - IUGU IP S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '402','bank'=>'402 - COBUCCIO SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '403','bank'=>'403 - CORA SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '404','bank'=>'404 - SUMUP SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '406','bank'=>'406 - ACCREDITO SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '407','bank'=>'407 - ÍNDIGO INVESTIMENTOS DTVM LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '408','bank'=>'408 - BONUSPAGO SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '410','bank'=>'410 - PLANNER SCM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '411','bank'=>'411 - VIA CERTA FINANCIADORA S.A. - CFI']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '412','bank'=>'412 - SOCIAL BANK S/A']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '413','bank'=>'413 - BCO BV S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '414','bank'=>'414 - WORK SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '416','bank'=>'416 - LAMARA SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '418','bank'=>'418 - ZIPDIN SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '419','bank'=>'419 - NUMBRS SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '421','bank'=>'421 - CC LAR CREDI']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '422','bank'=>'422 - BCO SAFRA S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '423','bank'=>'423 - COLUNA S.A. DTVM']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '425','bank'=>'425 - SOCINAL S.A. CFI']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '426','bank'=>'426 - BIORC FINANCEIRA - CFI S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '427','bank'=>'427 - CRED-UFES']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '428','bank'=>'428 - CREDSYSTEM SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '429','bank'=>'429 - CREDIARE CFI S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '430','bank'=>'430 - CCR SEARA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '433','bank'=>'433 - BR-CAPITAL DTVM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '435','bank'=>'435 - DELCRED SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '438','bank'=>'438 - TRUSTEE DTVM LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '439','bank'=>'439 - ID CTVM']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '440','bank'=>'440 - CREDIBRF COOP']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '442','bank'=>'442 - MAGNETIS - DTVM']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '443','bank'=>'443 - CREDIHOME SCD']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '444','bank'=>'444 - TRINUS SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '445','bank'=>'445 - PLANTAE CFI']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '447','bank'=>'447 - MIRAE ASSET CCTVM LTDA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '448','bank'=>'448 - HEMERA DTVM LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '449','bank'=>'449 - DMCARD SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '450','bank'=>'450 - FITBANK PAGAMENTOS ELETRONICOS S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '451','bank'=>'451 - J17 - SCD S/A']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '452','bank'=>'452 - CREDIFIT SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '454','bank'=>'454 - MÉRITO DTVM LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '456','bank'=>'456 - BCO MUFG BRASIL S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '457','bank'=>'457 - UY3 SCD S/A']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '458','bank'=>'458 - HEDGE INVESTMENTS DTVM LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '459','bank'=>'459 - CCM SERV. PÚBLICOS SP']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '460','bank'=>'460 - UNAVANTI SCD S/A']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '461','bank'=>'461 - ASAAS IP S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '462','bank'=>'462 - STARK SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '463','bank'=>'463 - AZUMI DTVM']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '464','bank'=>'464 - BCO SUMITOMO MITSUI BRASIL S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '465','bank'=>'465 - CAPITAL CONSIG SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '467','bank'=>'467 - MASTER S/A CCTVM']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '468','bank'=>'468 - PORTOSEG S.A. CFI']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '469','bank'=>'469 - LIGA INVEST DTVM LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '470','bank'=>'470 - CDC SOCIEDADE DE CRÉDITO']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '471','bank'=>'471 - CECM SERV PUBL PINHÃO']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '473','bank'=>'473 - BCO CAIXA GERAL BRASIL S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '475','bank'=>'475 - BCO YAMAHA MOTOR S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '477','bank'=>'477 - CITIBANK N.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '478','bank'=>'478 - GAZINCRED S.A. SCFI']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '479','bank'=>'479 - BCO ITAUBANK S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '481','bank'=>'481 - SUPERLÓGICA SCD S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '484','bank'=>'484 - MAF DTVM SA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '487','bank'=>'487 - DEUTSCHE BANK S.A.BCO ALEMAO']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '488','bank'=>'488 - JPMORGAN CHASE BANK']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '492','bank'=>'492 - ING BANK N.V.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '495','bank'=>'495 - BCO LA PROVINCIA B AIRES BCE']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '505','bank'=>'505 - BCO CREDIT SUISSE S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '506','bank'=>'506 - RJI']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '508','bank'=>'508 - AVENUE SECURITIES DTVM LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '511','bank'=>'511 - MAGNUM SCD']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '512','bank'=>'512 - CAPTALYS DTVM LTDA.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '545','bank'=>'545 - SENSO CCVM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '600','bank'=>'600 - BCO LUSO BRASILEIRO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '604','bank'=>'604 - BCO INDUSTRIAL DO BRASIL S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '610','bank'=>'610 - BCO VR S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '611','bank'=>'611 - BCO PAULISTA S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '612','bank'=>'612 - BCO GUANABARA S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '613','bank'=>'613 - OMNI BANCO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '623','bank'=>'623 - BANCO PAN']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '626','bank'=>'626 - BCO C6 CONSIG']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '630','bank'=>'630 - BCO LETSBANK S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '633','bank'=>'633 - BCO RENDIMENTO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '634','bank'=>'634 - BCO TRIANGULO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '637','bank'=>'637 - BCO SOFISA S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '643','bank'=>'643 - BCO PINE S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '652','bank'=>'652 - ITAÚ UNIBANCO HOLDING S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '653','bank'=>'653 - BANCO VOITER']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '654','bank'=>'654 - BCO DIGIMAIS S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '655','bank'=>'655 - BCO VOTORANTIM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '707','bank'=>'707 - BCO DAYCOVAL S.A']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '712','bank'=>'712 - BCO OURINVEST S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '720','bank'=>'720 - BCO RNX S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '739','bank'=>'739 - BCO CETELEM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '741','bank'=>'741 - BCO RIBEIRAO PRETO S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '743','bank'=>'743 - BANCO SEMEAR']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '745','bank'=>'745 - BCO CITIBANK S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '746','bank'=>'746 - BCO MODAL S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '747','bank'=>'747 - BCO RABOBANK INTL BRASIL S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '748','bank'=>'748 - BCO COOPERATIVO SICREDI S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '751','bank'=>'751 - SCOTIABANK BRASIL']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '752','bank'=>'752 - BCO BNP PARIBAS BRASIL S A']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '753','bank'=>'753 - NOVO BCO CONTINENTAL S.A. - BM']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '754','bank'=>'754 - BANCO SISTEMA']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '755','bank'=>'755 - BOFA MERRILL LYNCH BM S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '756','bank'=>'756 - BANCO SICOOB S.A.']);
        DB::table('banks')->insert(['created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),'bank_number'=> '757','bank'=>'757 - BCO KEB HANA DO BRASIL S.A.']);
    }
}